[workspace]
resolver = "3"
members = [
    "chiaro-rs/actions",
    "chiaro-rs/chiaro",
    "chiaro-rs/config",
    "chiaro-rs/dashboard-ui",
    "chiaro-rs/ibt-picker",
    "chiaro-rs/irsdk",
    "chiaro-rs/live-telemetry",
    "chiaro-rs/navigation-ui",
    "chiaro-rs/settings-ui",
    "chiaro-rs/telemetry",
    "chiaro-rs/theme",
    "chiaro-rs/time-series-chart",
    "chiaro-rs/tray",
    "chiaro-rs/window",
]

[workspace.package]
version = "0.1.0"
authors = ["Ryuji Ishimi"]
edition = "2024"
rust-version = "1.96"
publish = true
license = "GPL-3.0-or-later"

[workspace.dependencies]
bitflags = "2.13.0"
chiaro = { version = "0.1.0", path = "chiaro-rs/chiaro" }
chiaro-actions = { version = "0.1.0", path = "chiaro-rs/actions" }
chiaro-config = { version = "0.1.0", path = "chiaro-rs/config" }
chiaro-dashboard-ui = { version = "0.1.0", path = "chiaro-rs/dashboard-ui" }
chiaro-ibt-picker = { version = "0.1.0", path = "chiaro-rs/ibt-picker" }
chiaro-live-telemetry = { version = "0.1.0", path = "chiaro-rs/live-telemetry" }
chiaro-navigation-ui = { version = "0.1.0", path = "chiaro-rs/navigation-ui" }
chiaro-settings-ui = { version = "0.1.0", path = "chiaro-rs/settings-ui" }
chiaro-theme = { version = "0.1.0", path = "chiaro-rs/theme" }
chiaro-time-series-chart = { version = "0.1.0", path = "chiaro-rs/time-series-chart" }
chiaro-tray = { version = "0.1.0", path = "chiaro-rs/tray" }
chiaro-window = { version = "0.1.0", path = "chiaro-rs/window" }
chiaroscuro-irsdk = { version = "0.1.0", path = "chiaro-rs/irsdk" }
chiaroscuro-telemetry = { version = "0.1.0", path = "chiaro-rs/telemetry" }
config = "0.15.25"
encoding_rs = "0.8.35"
iced = { version = "0.14.0", features = ["smol"] }
iced_fonts = { version = "0.3.0", default-features = false, features = ["lucide"] }
iced_plot = "0.5.0"
image = { version = "0.25.8", default-features = false, features = ["png"] }
rpmalloc = "0.2.2"
rfd = "0.17.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml_ng = "0.10.0"
smol = "2.0.2"
tray-icon = "0.24.1"
winapi = { version = "0.3.9", features = [
    "handleapi",
    "memoryapi",
    "processthreadsapi",
    "synchapi",
    "winbase",
    "winerror",
    "winnt",
] }

[workspace.lints.rust]
missing_debug_implementations = "warn"
dead_code = "warn"

[workspace.lints.clippy]
type-complexity = "allow"
map-entry = "allow"
large-enum-variant = "allow"
result_large_err = "allow"
semicolon_if_nothing_returned = "deny"
trivially-copy-pass-by-ref = "deny"
match-wildcard-for-single-variants = "deny"
redundant-closure-for-method-calls = "deny"
filter_map_next = "deny"
manual_let_else = "deny"
unused_async = "deny"
from_over_into = "deny"
needless_borrow = "deny"
useless_conversion = "deny"

[profile.release]
opt-level = 3
debug = false
strip = "debuginfo"
overflow-checks = false
lto = "fat"
panic = "unwind"
codegen-units = 1
incremental = false

[profile.dev]
opt-level = 0
debug = "line-tables-only"
split-debuginfo = "unpacked"
strip = false
overflow-checks = true
lto = "off"
panic = "unwind"
codegen-units = 256
incremental = true
