[package]
name = "chiaroscuro-irsdk"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "chiaro-irsdk"
path = "src/irsdk.rs"

[dependencies]
anyhow = { workspace = true }
async-channel = { workspace = true }
config = { workspace = true }
rpmalloc = { workspace = true }
serde = { workspace = true }
smol = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }
