[package]
name = "chiaro_window"
description = "Custom window chrome and lifecycle handling for the Chiaro desktop application."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/window.rs"

[dependencies]
chiaro_i18n = { workspace = true }
chiaro_widgets = { workspace = true }
iced = { workspace = true, features = ["image-without-codecs"] }
image = { workspace = true }
