[package]
name = "chiaroscuro-chiaro"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "chiaro"
path = "src/chiaro.rs"

[dependencies]
config = { workspace = true }
iced = { workspace = true }
iced_aw = { workspace = true }
iced_fonts = { workspace = true }
iced_plot = { workspace = true }
rpmalloc = { workspace = true }
serde = { workspace = true }
smol = { workspace = true }
