[package]
name = "chiaro"
description = "Desktop executable for Chiaroscuro."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "chiaro"
path = "src/chiaro.rs"

[dependencies]
chiaro-actions = { workspace = true }
chiaro-config = { workspace = true }
chiaro-dashboard-ui = { workspace = true }
chiaro-ibt-picker = { workspace = true }
chiaro-live-telemetry = { workspace = true }
chiaro-navigation-ui = { workspace = true }
chiaro-settings-ui = { workspace = true }
chiaro-theme = { workspace = true }
chiaro-tray = { workspace = true }
chiaro-window = { workspace = true }
chiaroscuro-telemetry = { workspace = true }
iced = { workspace = true }
iced_fonts = { workspace = true }
rpmalloc = { workspace = true }
