[package]
name = "chiaro_settings_ui"
description = "Settings state, updates, and view for the Chiaro desktop application."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/settings_ui.rs"

[dependencies]
chiaro_actions = { workspace = true }
chiaro_widgets = { workspace = true }
chiaro_irsdk = { workspace = true }
chiaro_telemetry = { workspace = true }
iced = { workspace = true }
